SELECT INDUSTRY AS "Industria", SUM(S.PROFIT) AS "Beneficio Total",
        CASE 
            WHEN SUM(S.PROFIT)<1000000 THEN 'Alto'
            ELSE 'Normal'
        END AS "Categoría según el beneficio"
FROM ACCOUNT AS A JOIN SALES AS S
ON A.ACCOUNT=S.ACCOUNT
WHERE A.ACCOUNT IN( SELECT DISTINCT F.ACCOUNT
    FROM FORECASTS AS F
    WHERE F.PREDICTION_CATEGORY='Commit' AND FORECAST>500000)
GROUP BY A.INDUSTRY  
ORDER BY "Beneficio Total" DESC;