SELECT COALESCE(S.CATEGORY, F.CATEGORY) AS "Categoria", SUM(PROFIT) AS "Beneficio", 
SUM(CASE WHEN F.YEAR=2022 THEN F.FORECAST
        ELSE 0 END ) AS "Previsión Beneficio", MIN(CASE WHEN F.YEAR=2022 THEN F.OPPORTUNITY_AGE ELSE NULL END) AS "Oportunidad Mas Reciente", MAX(CASE WHEN F.YEAR=2022 THEN F.OPPORTUNITY_AGE ELSE NULL END) AS "Oportunidad Mas Antigua"
FROM SALES AS S FULL OUTER JOIN FORECASTS AS F 
ON S.CATEGORY=F.CATEGORY AND S.YEAR=F.YEAR
WHERE S.YEAR=2021 OR F.YEAR=2022
GROUP BY COALESCE(S.CATEGORY, F.CATEGORY);