SELECT A.ACCOUNT_EXECUTIVE AS "Ejecutivo de cuentas", SUM(S.PROFIT) AS "Beneficio Total", COUNT(DISTINCT A.ACCOUNT) AS "Numero de Cuentas Gestionadas", CAST(SUM(S.PROFIT)/COUNT(DISTINCT A.ACCOUNT) AS DECIMAL(18,2) ) AS "Beneficio Promedio por Cuenta"
FROM ACCOUNT AS A JOIN SALES AS S
ON A.ACCOUNT=S.ACCOUNT
GROUP BY A.ACCOUNT_EXECUTIVE
ORDER BY "Beneficio Promedio por Cuenta" DESC;


SELECT *
FROM JUGADOR 
WHERE DEUDA>1000000 AND EDAD<30;

SELECT ID, NOMBRE, A.EQUIPO, RESULTADO
FROM JUGADOR AS A JOIN EQUIPOS AS E
ON A.EQUIPO=E.EQUIPO
WHERE RESULTADO='GANADOR'

